import pptxgen from 'pptxgenjs';

export const generatePPTX = async (title = 'Presentation', structuredData = {}) => {
  const pres = new pptxgen();
  pres.layout = 'LAYOUT_16x9';

  // Title Slide
  const titleSlide = pres.addSlide();
  titleSlide.background = { color: '0F172A' }; // Slate-900

  titleSlide.addText(structuredData.title || title, {
    x: 1.0,
    y: 2.0,
    w: 11.33,
    h: 1.8,
    fontSize: 36,
    bold: true,
    color: 'FFFFFF',
    align: 'left',
  });

  titleSlide.addText('Generated by ContentForge AI · Multi-Format Transformation Engine', {
    x: 1.0,
    y: 4.0,
    w: 11.33,
    h: 0.8,
    fontSize: 16,
    color: '94A3B8', // Slate-400
    align: 'left',
  });

  // Content Slides
  const slides = Array.isArray(structuredData.slides) ? structuredData.slides : [];

  for (const slideData of slides) {
    const slide = pres.addSlide();
    slide.background = { color: 'F8FAFC' };

    // Slide Header
    slide.addText(slideData.title || 'Slide Title', {
      x: 0.8,
      y: 0.6,
      w: 11.5,
      h: 0.8,
      fontSize: 24,
      bold: true,
      color: '0F172A',
    });

    // Bullets list
    if (Array.isArray(slideData.bullets) && slideData.bullets.length > 0) {
      const bulletItems = slideData.bullets.map((b) => ({
        text: b,
        options: { fontSize: 16, color: '334155', breakLine: true, bullet: true },
      }));

      slide.addText(bulletItems, {
        x: 0.8,
        y: 1.6,
        w: slideData.visualRecommendation ? 7.0 : 11.5,
        h: 4.5,
        align: 'left',
        valign: 'top',
        lineSpacing: 28,
      });
    }

    // Visual Recommendation Box if present
    if (slideData.visualRecommendation) {
      slide.addShape(pres.ShapeType.rect, {
        x: 8.2,
        y: 1.6,
        w: 4.3,
        h: 4.5,
        fill: { color: 'EFF6FF' }, // Light blue
        line: { color: '93C5FD', width: 1 },
      });

      slide.addText('💡 VISUAL RECOMMENDATION:\n' + slideData.visualRecommendation, {
        x: 8.4,
        y: 1.8,
        w: 3.9,
        h: 4.0,
        fontSize: 13,
        color: '1E40AF',
        valign: 'top',
      });
    }

    // Speaker Notes
    if (slideData.speakerNotes) {
      slide.addNotes(slideData.speakerNotes);
    }

    // Footer
    slide.addText('ContentForge AI · Automated Knowledge Preservation', {
      x: 0.8,
      y: 6.8,
      w: 11.5,
      h: 0.3,
      fontSize: 9,
      color: '94A3B8',
    });
  }

  const buffer = await pres.write({ outputType: 'nodebuffer' });
  return buffer;
};
